[[services]]
name = "backend"
path = "backend"
[services.build]
builder = "python"
install = ["pip install -r requirements.txt"]
start = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "frontend"
path = "frontend"
[services.build]
builder = "node"
install = ["yarn install"]
build = "yarn build"
start = "yarn start"
